name = "contact-form-worker-resend"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
RESEND_API_ENDPOINT = "https://api.resend.com/emails"
ALLOWED_ORIGIN = "https://josematoswork.com"
EMAIL_FROM = "Contact Form <noreply@josematoswork.com>"
EMAIL_TO = "developer@josematoswork.com"
LIMIT_PER_DAY = 5

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV_STORE"
id = "d734ed9914ca45bda855657fbee4e8ec"
preview_id = "d734ed9914ca45bda855657fbee4e8ec"